# Generated by Django 3.0 on 2022-08-20 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_evento',
        ),
    ]
